### ISSUE TITLE
Add support for .deb files which have control.tar.xz

### ISSUE THREAD

**Issue by sevenpastzeero** [TheClimateCorporation/python-dpkg#10]
I am using python-dpkg with dpkg-scanpackages.py in order to scan a folder for deb files and create a Package.bz2
But if a deb file is compressed with xz instead of gzip I get this error

```
Traceback (most recent call last):
  File "site-packages\pydpkg\__init__.py", line 282, in _process_dpkg_file
KeyError: b'control.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dpkg-scanpackages-script.py", line 173, in <module>
  File "dpkg-scanpackages-script.py", line 167, in main
  File "dpkg-scanpackages-script.py", line 108, in scan
  File "dpkg-scanpackages-script.py", line 82, in __get_packages
  File "dpkg-scanpackages-script.py", line 32, in __init__
  File "site-packages\pydpkg\__init__.py", line 157, in headers
  File "site-packages\pydpkg\__init__.py", line 137, in message
  File "site-packages\pydpkg\__init__.py", line 285, in _process_dpkg_file
pydpkg.DpkgMissingControlGzipFile: Corrupt dpkg file: no control.tar.gz file in ar archive.
[9104] Failed to execute script dpkg-scanpackages-script
```

Anyway to fix it

**Comment by memory** [comment]
Interesting.  Can you provide a sample of a package file that it choked on?

**Comment by sevenpastzeero** [comment]
Here is is two debs. one compressed with gzip, the other with xz.
When I use this script [dpkg-scanpackages-py](https://github.com/supermamon/dpkg-scanpackages-py) create a Packages file. The gzip one passthrough ok and the Packages file gets created/updated. The xz one on the other hand gives me errors.
```

D:\Zaid\Desktop\test>D:\zaid\Desktop\test\dpkg-scanpackages-script.py D:\zaid\Desktop\test -o Packages
Traceback (most recent call last):
  File "C:\Users\zaid\AppData\Local\Programs\Python\Python37\lib\site-packages\pydpkg\__init__.py", line 282, in _process_dpkg_file
    control_tgz = dpkg_archive.archived_files[b'control.tar.gz']
KeyError: b'control.tar.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\zaid\Desktop\test\dpkg-scanpackages-script.py", line 173, in <module>
    main()
  File "D:\zaid\Desktop\test\dpkg-scanpackages-script.py", line 167, in main
    output=args.output
  File "D:\zaid\Desktop\test\dpkg-scanpackages-script.py", line 108, in scan
    self.__get_packages()
  File "D:\zaid\Desktop\test\dpkg-scanpackages-script.py", line 82, in __get_packages
    pkg_info = DpkgInfo(fname)
  File "D:\zaid\Desktop\test\dpkg-scanpackages-script.py", line 32, in __init__
    self.headers = pkg.headers
  File "C:\Users\zaid\AppData\Local\Programs\Python\Python37\lib\site-packages\pydpkg\__init__.py", line 157, in headers
    self._headers = dict(self.message.items())
  File "C:\Users\zaid\AppData\Local\Programs\Python\Python37\lib\site-packages\pydpkg\__init__.py", line 137, in message
    self._message = self._process_dpkg_file(self.filename)
  File "C:\Users\zaid\AppData\Local\Programs\Python\Python37\lib\site-packages\pydpkg\__init__.py", line 285, in _process_dpkg_file
    'Corrupt dpkg file: no control.tar.gz file in ar archive.')
pydpkg.DpkgMissingControlGzipFile: Corrupt dpkg file: no control.tar.gz file in ar archive.

D:\Zaid\Desktop\test>

```


https://drive.google.com/open?id=1q6F6roXRHlEZ4yaDX_OWuk024Q98I9nt

**Comment by uafio** [comment]
I'm encountering the same issue, here is example package.

http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.27-3ubuntu1_amd64.deb

Package: libc6-dbg
Architecture: amd64
Version: 2.27-3ubuntu1
Multi-Arch: same
Priority: extra
Section: debug
Source: glibc
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 39460
Provides: libc-dbg
Depends: libc6 (= 2.27-3ubuntu1)
Filename: pool/main/g/glibc/libc6-dbg_2.27-3ubuntu1_amd64.deb
Size: 5160716
MD5sum: 63362a59f2f0d34cc8caadb49119b06a
SHA1: e5f56ff83187f1dff2813c23e04778944744c079
SHA256: 864bf8edabe18c708b0b12a6253aba4917e914241c3723c603aba9e9a84b38f8
Homepage: https://www.gnu.org/software/libc/libc.html
Description: GNU C Library: detached debugging symbols
Task: ubuntu-desktop, kubuntu-desktop, kubuntu-full, xubuntu-desktop, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Description-md5: bbc98343da14bf76d4a45c2181fd8902
Supported: 5y

$ ar t libc6-dbg_2.27-3ubuntu1_amd64.deb
debian-binary
control.tar.xz
data.tar.xz

Thanks,

**Comment by memory** [comment]
Thanks folks!  I'll try to get a fix put together in the next day or two; this looks reasonably straightforward to support.

**Comment by memory** [comment]
Versions 1.4.1 and 1.3.2 have been released with this fix.
